#!/bin/bash

# Bash Colors
red="\e[1;31m"; green="\e[1;32m"; yellow="\e[1;33m"
blue="\e[1;34m"; cyan="\e[1;36m"; nc="\e[0m"


_test() {
    echo -e "${red}Install Test${nc}"
    yaourt --noconfirm -S gparted
}

_test | cp /dev/stdin "_test.log"
