#!/bin/bash

#                        ARCH LINUX BASE SYSTEM
# ============================================================================
# Here we install Arch Linux base system with the chosen linux kernel.
# We use reflector service to automate mirrorlist sorting.
# We install CPU microcode updates <intel-ucode> or <amd-ucode>.
# We create user account with the previously defined password.
# Then we install an AUR Helper (optional), yay and trizen supported.
# Finally we clean pacman cache and remove unrequired dependencies.
#
# All steps are described in the official documentation:
#
#   https://wiki.archlinux.org/index.php/Installation_guide
# ============================================================================

_install_base() {

    # Base System
    _info "Installing base system with ${KERNEL_NAME,,} kernel"
    yes '' | pacstrap /mnt ${ARCH} ${!KERNEL}

    # Fstab
    _info "Setting file systems table"
    genfstab -U -p /mnt >> /mnt/etc/fstab
    cat /mnt/etc/fstab

    # Timezone
    _info "Setting timezone to ${TIMEZONE}"
    ln -sfv /usr/share/zoneinfo/${TIMEZONE} /mnt/etc/localtime

    # Locale
    _info "Setting locale to ${LANGUAGE}.UTF-8"
    echo "${LANGUAGE}.UTF-8 UTF-8" >> /mnt/etc/locale.gen
    _chroot "locale-gen"
    _chroot "export LANG=${LANGUAGE}.UTF-8"
    echo "LANG=${LANGUAGE}.UTF-8" > /mnt/etc/locale.conf

    # Vconsole
    _info "Setting virtual console to ${KEYMAP^^}"
    echo "KEYMAP=${KEYMAP}" > /mnt/etc/vconsole.conf

    # Hostname
    _info "Setting hostname ${HOST_NAME}"
    echo ${HOST_NAME} > /mnt/etc/hostname

    # Root passwd
    _info "Setting root password"
    _chroot "echo 'root:${ROOTPASSWD}' | chpasswd"

    # Network
    _info "Installing network manager"
    _chroot "pacman --noconfirm --needed -S ${NETAPPS}"
    _chroot "systemctl enable NetworkManager"
    _chroot "systemctl enable ntpd"

    # Microcode
    MICROCODE=$(lscpu | grep "Intel")
    if [[ ${MICROCODE} ]]; then
        _info "Installing Intel CPU Microcode"
        _chroot "pacman --noconfirm --needed -S ${INTEL_UCODE}"
        export MICROCODE="intel"
    else
        MICROCODE=$(lscpu | grep "AMD")
        if [[ ${MICROCODE} ]]; then
            _info "Installing AMD CPU Microcode"
            _chroot "pacman --noconfirm --needed -S ${AMD_UCODE}"
            export MICROCODE="amd"
        fi
    fi

    # User
    _info "Setting user ${USER_NAME}"
    _chroot "useradd -g users -m -s /bin/bash ${USER_NAME}"
    _chroot "echo '${USER_NAME}:${USERPASSWD}' | chpasswd"
}

_install_AUR_helper() {
    _info "Installing ${AUR_HELPER,,} AUR Helper"
    sed -i -e \
"s/${USER_NAME} ALL=(ALL) ALL/${USER_NAME} ALL=(ALL) NOPASSWD: ALL/g" \
/etc/sudoers
    _chroot "cd /home/${USER_NAME} && sudo -u ${USER_NAME} git clone \
https://aur.archlinux.org/${AUR_HELPER,,}.git"
    _chroot "cd /home/${USER_NAME}/${AUR_HELPER,,} && sudo -u ${USER_NAME} \
makepkg --noconfirm --needed -sic"
    sed -i -e \
"s/${USER_NAME} ALL=(ALL) NOPASSWD: ALL/${USER_NAME} ALL=(ALL) ALL/g" \
/etc/sudoers
    rm -rf /mnt/home/${USER_NAME}/${AUR_HELPER,,}
}

_clean_dependencies() {
    _info "Cleaning cache and unrequired dependencies"
    UNREQUIRED_DEPENDENCIES=$(_chroot "pacman -Qdtq")
    if [[ ${UNREQUIRED_DEPENDENCIES} ]]; then
        _chroot "pacman --noconfirm -Rcsn ${UNREQUIRED_DEPENDENCIES}"
    fi
    _chroot "pacman --noconfirm -Sc"
}

# archboot by grm34 under Apache License 2.0
# ============================================================================
