#!/bin/bash

#                        ARCH LINUX BASE SYSTEM
# ============================================================================
# Here we install Arch Linux base system with the chosen linux kernel.
# All steps are described in the official documentation:
# https://wiki.archlinux.org/index.php/Installation_guide
# We use reflector service to automate mirrorlist sorting.
# In case of Intel CPU we install <intel-ucode> to enable microcode updates.
# Then we create user account with the previously defined password.
# ============================================================================

_install_base() {

    # Base System
    _info "Installing base system with linux ${KERNEL_NAME,,}"
    yes '' | pacstrap /mnt ${ARCH} ${!KERNEL}

    # fstab
    _info "Setting file systems table"
    genfstab -U -p /mnt >> /mnt/etc/fstab
    cat /mnt/etc/fstab

    # Timezone
    _info "Setting timezone to ${TIMEZONE}"
    ln -sf /usr/share/zoneinfo/${TIMEZONE} /mnt/etc/localtime

    # locale
    _info "Setting locale to ${LANGUAGE}.UTF-8"
    echo "${LANGUAGE}.UTF-8 UTF-8" >> /mnt/etc/locale.gen
    _chroot "locale-gen"
    _chroot "export LANG=${LANGUAGE}.UTF-8"
    echo "LANG=${LANGUAGE}.UTF-8" > /mnt/etc/locale.conf

    # vconsole
    _info "Setting virtual console to ${KEYMAP^^}"
    echo "KEYMAP=${KEYMAP}" > /mnt/etc/vconsole.conf

    # hostname
    _info "Setting hostname ${HOST_NAME}"
    echo ${HOST_NAME} > /mnt/etc/hostname

    # root passwd
    _info "Setting root password"
    _chroot "echo 'root:${ROOTPASSWD}' | chpasswd"

    # network
    _info "Installing network manager"
    _chroot "pacman --noconfirm -S ${NETAPPS}"
    _chroot "systemctl enable NetworkManager"

    # reflector
    _info "Installing reflector service"
    _chroot "pacman --noconfirm -S ${REFLECTOR}"
    mv reflector /mnt/etc/systemd/system/reflector.service
    _chroot "systemctl enable reflector.service"

    # Intel Microcode
    MICROCODE=$(lscpu | grep "Intel")
    if [[ ${MICROCODE} ]]; then
        _info "Installing Intel CPU Microcode"
        _chroot "pacman --noconfirm -S ${INTEL_UCODE}"
        export MICROCODE="True"
    fi

    # user
    _info "Setting user ${USER_NAME}"
    _chroot "useradd -g users -m -s /bin/bash ${USER_NAME}"
    _chroot "echo '${USER_NAME}:${USERPASSWD}' | chpasswd"
}

# archboot by grm34 under Apache License 2.0
# ============================================================================
