#!/bin/bash

# ARCHBOOT BASE SYSTEM
# ============================================================================
# Here we install base system, all steps are described in the official
# documentation: https://wiki.archlinux.org/index.php/Installation_guide
# User can choose to enable AUR support and/or Multilib support.
# In case of Intel CPU we install intel microcode to enable microcode updates.
# And if full rights given to the user we add him to sudoers with ALL power.

_base() {

    # Base System
    _info "Installing base system"
    yes '' | pacstrap /mnt ${_arch}

    # fstab
    _info "Setting and generating fstab"
    genfstab -U -p /mnt >> /mnt/etc/fstab

    # TimeZone
    _info "Setting time zone"
    ln -sf /usr/share/zoneinfo/${timezone} /mnt/etc/localtime

    # locale
    _info "Setting and generating locale"
    echo "${language}.UTF-8 UTF-8" >> /mnt/etc/locale.gen
    _chroot "locale-gen
    export LANG=${language}.UTF-8"
    echo "LANG=${language}.UTF-8" > /mnt/etc/locale.conf

    # keyboard
    _info "Setting vconsole"
    echo "KEYMAP=${keymap_code}" > /mnt/etc/vconsole.conf

    # hostname
    _info "Setting hostname"
    echo "${HOST_name}" > /mnt/etc/hostname

    # initramfs
    _info "Setting initramfs"
    _chroot "mkinitcpio -p linux"

    # root passwd
    _info "Setting root password"
    _chroot "echo 'root:${ROOT_passwd}' | chpasswd"

    # Multilib support
    if [[ ! -z ${multilib+x} ]]; then
        _info "Enabling multilib support"
        sed -i -e "/multilib]/,/mirrorlist/ s/#//g" /mnt/etc/pacman.conf
        _chroot "pacman --noconfirm -Syu"
    fi

    # AUR support
    if [[ ! -z ${aur+x} ]]; then
        _info "Enabling AUR support"
        echo -e "\n[archlinuxfr]" >> /mnt/etc/pacman.conf
        echo -e "SigLevel = Never" >> /mnt/etc/pacman.conf
        echo -e "Server = http://repo.archlinux.fr/\$arch" \
        >> /mnt/etc/pacman.conf
        _info "Installing yaourt"
        _chroot "pacman --noconfirm -Syu ${_yaourtapps}"
    fi

    # network
    _info "Installing network"
    _chroot "pacman --noconfirm -S ${_netapps}
    systemctl enable NetworkManager"

    # Intel Microcode
    lscpu | grep "Intel" >/dev/null 2>&1
    if [[ $? -eq 0 ]]; then
        _info "Installing Intel CPU Microcode"
        _chroot "pacman --noconfirm -S ${_intel}"
    fi

    # user
    _info "Setting user ${USER_name}"
    _chroot "useradd -g users -m -s /bin/bash ${USER_name}
    echo '${USER_name}:${USER_passwd}' | chpasswd"
    if [[ ! -z ${power+x} ]]; then
        echo "${USER_name} ALL=(ALL) ALL" >> /mnt/etc/sudoers
    fi
}
