#!/bin/bash

#                             BOOTLOADER
# ============================================================================
# Here we install and configure bootloader, systemd-boot for UEFI and
# Grub2 for BIOS (with additional themes for beautifull OS selection menu).
#
# All steps are described in the official documentation:
#
#   UEFI...: https://wiki.archlinux.org/index.php/Systemd-boot
#   BIOS...: https://wiki.archlinux.org/index.php/GRUB
# ============================================================================

_install_bootloader() {

    # UEFI Firmware > systemd-boot
    if [[ ${FIRMWARE} == "UEFI" ]]; then

        # Install systemd-boot
        _info "Installing systemd-boot on ${BOOT_PARTITION}"
        _chroot "bootctl --path=/boot install"

        # Replace loader.conf
        _info "Setting systemd-boot loader"
        echo "downloading loader.conf..."
        _wget ${URL}/conf/loader.conf
        mv -v /mnt/boot/loader/loader.conf /mnt/boot/loader/loader.backup
        mv -v loader.conf /mnt/boot/loader/loader.conf
        echo "done"

        # Create new boot entry
        _info "Setting systemd-boot entry"
        BOOTCONF="/mnt/boot/loader/entries/arch.conf"
        echo "title Arch Linux" > ${BOOTCONF}
        echo "linux /vmlinuz-${KERNEL_NAME,,}" >> ${BOOTCONF}
        case ${MICROCODE} in
            intel|amd)
                echo "initrd /${MICROCODE}-ucode.img" >> ${BOOTCONF}
                ;;
        esac
        echo "initrd /initramfs-${KERNEL_NAME,,}.img" >> ${BOOTCONF}
        echo "options root=${SYSTEM_PARTITION} quiet splash rw" >> ${BOOTCONF}
        echo "done"

        # Update systemd-boot
        _info "Updating systemd-boot config"
        _chroot "bootctl --path=/boot update"

    # BIOS Firmware > Grub2
    else

        # Install Grub2
        _info "Installing Grub bootloader"
        _chroot "pacman --noconfirm --needed -S ${GRUB}"
        _chroot "grub-install --target=i386-pc ${DRIVE}"

        # Download Themes
        _info "Downloading Grub Themes"
        _wget ${GHPAGES}/assets/images/background.png && echo
        _chroot "git clone git://github.com/Generator/Grub2-themes.git"

        # Install Themes
        _info "Installing Grub Themes"
        _chroot "cp -r Grub2-themes/{Archlinux,Archxion} /boot/grub/themes/"
        sed -i -e "s/GRUB_GFXMODE=auto/GRUB_GFXMODE=1024x768/g" \
/mnt/etc/default/grub
        echo "GRUB_THEME=/boot/grub/themes/Archlinux/theme.txt" \
>> /mnt/etc/default/grub
        echo "desktop-image: \"background.png\"" \
>> /mnt/boot/grub/themes/Archlinux/theme.txt
        mv background.png /mnt/boot/grub/themes/Archlinux/background.png
        rm -rf /mnt/Grub2-themes
        echo "done"

        # Configure Grub2
        _info "Setting Grub bootloader"
        _chroot "grub-mkconfig -o /boot/grub/grub.cfg"
    fi
}

# archboot by grm34 under Apache License 2.0
# ============================================================================
