#!/bin/bash

#                             BOOTLOADER
# ============================================================================
# Here we install and configure bootloader, systemd-boot for UEFI and
# Grub for BIOS (with additional themes for beautifull OS selection menu).
#
# All steps are described in the official documentation:
#
#   UEFI...: https://wiki.archlinux.org/index.php/Systemd-boot
#   BIOS...: https://wiki.archlinux.org/index.php/GRUB
# ============================================================================

_install_bootloader() {

    ### UEFI Firmware > systemd-boot
    if [[ ${FIRMWARE} == "UEFI" ]]; then

        # Install systemd-boot
        _info "${MSG_INSTALL_SYSTEMDBOOT} ${BOOT_PARTITION}"
        _chroot "bootctl --path=/boot install"
        echo "-> ${MSG_DONE}"

        # Replace loader.conf
        _info "${MSG_SYSTEMDBOOT_LOADER}"
        echo "-> ${MSG_DOWNLOADING} loader.conf..."
        _wget "${URL}/src/conf/loader.conf" && echo
        mv -v /mnt/boot/loader/loader.conf /mnt/boot/loader/loader.backup
        mv -v loader.conf /mnt/boot/loader/loader.conf
        echo "-> ${MSG_DONE}"

        # Get root partition UUID
        ROOT_UUID=$(blkid -o value -s UUID "${SYSTEM_PARTITION}")

        # Create new boot entry
        _info "${MSG_SYSTEMDBOOT_ENTRY}"
        BOOTCONF="/mnt/boot/loader/entries/arch.conf"
        echo "title Arch Linux" > "${BOOTCONF}"
        echo "linux /vmlinuz-${KERNEL_NAME,,}" >> "${BOOTCONF}"

        case ${UCODE} in
            intel|amd) echo "initrd /${UCODE}-ucode.img" >> "${BOOTCONF}"
        esac

        echo "initrd /initramfs-${KERNEL_NAME,,}.img" >> "${BOOTCONF}"
        echo "options root=UUID=${ROOT_UUID} quiet splash rw" >> "${BOOTCONF}"
        echo "-> ${MSG_DONE}"

        # Update systemd-boot
        _info "${MSG_SYSTEMDBOOT_UPDATE}"
        _chroot "bootctl --path=/boot update"
        echo "-> ${MSG_DONE}"

    ### BIOS Firmware > Grub
    else

        # Install Grub
        _info "${MSG_INSTALL_GRUB} ${DRIVE}"
        _chroot "pacman --noconfirm --needed -S ${GRUB}"

        if [[ ${NTFS} ]]; then
            _chroot "pacman --noconfirm --needed -S ${GRUB_EXTRAS}"
        fi
        _chroot "grub-install --target=i386-pc ${DRIVE}"
        echo "-> ${MSG_DONE}"

        # Download Themes
        _info "${MSG_DL_GRUB_THEME}"
        _wget "${GHPAGES}/assets/images/background.png" && echo
        _chroot "git clone git://github.com/Generator/Grub2-themes.git"
        echo "-> ${MSG_DONE}"

        # Install Themes
        _info "${MSG_INSTALL_GRUB_THEME}"
        _chroot "cp -r Grub2-themes/{Archlinux,Archxion} /boot/grub/themes/"
        sed -i -e "s/GRUB_GFXMODE=auto/GRUB_GFXMODE=1024x768/g" \
/mnt/etc/default/grub
        echo "GRUB_THEME=/boot/grub/themes/Archlinux/theme.txt" \
>> /mnt/etc/default/grub
        echo "desktop-image: \"background.png\"" \
>> /mnt/boot/grub/themes/Archlinux/theme.txt
        mv background.png /mnt/boot/grub/themes/Archlinux/background.png
        rm -rf /mnt/Grub2-themes
        echo "-> ${MSG_DONE}"

        # Configure Grub
        _info "${MSG_SET_GRUB}"
        _chroot "grub-mkconfig -o /boot/grub/grub.cfg"
    fi
}

# archboot - Arch Linux Installer by grm34 under Apache License 2.0
# ============================================================================
