#!/bin/bash

#                       DESKTOP ENVIRONMENT
# ============================================================================
# Here we install desktop environment with the required packages
# such as display server, fonts (to prevent issues in gtk apps on
# some DE), <terminator> and <numlockx> (to get numlock on bootup).
# To prevent password issues on the login screen of the display manager
# caused by wrong keyboard layout, we add keyboard.conf to xorg settings.
#
# All steps are described in the official documentation:
#
#   https://wiki.archlinux.org/index.php/Desktop_environment
# ============================================================================

_install_desktop_environment() {

    # Xorg server
    _info "Installing xorg server"
    _chroot "pacman --noconfirm --needed -S ${XORG}"

    # Fonts
    _info "Installing fonts"
    _chroot "pacman --noconfirm --needed -S ${FONTS}"

    # Numlock
    _info "Installing numlock"
    _chroot "pacman --noconfirm --needed -S ${NUMLOCK}"

    # Terminal
    _info "Installing terminal"
    _chroot "pacman --noconfirm --needed -S ${TERMINAL}"

    case ${DESKTOP} in

        # Desktop Environment
        GNOME|KDE|MATE|XFCE4|LXDE|LXQT|DEEPIN|BUDGIE|CINNAMON|ENLIGHTENMENT)
            _info "Installing ${DESKTOP,,} desktop"
            _chroot "pacman --noconfirm --needed -S ${!DESKTOP}"
            ;;

        # Window Manager
        AWESOME|I3|XMONAD|BSPWM|HERBSTLUFTWM)

            # Xorg xinit
            _info "Installing xorg xinit"
            _chroot "pacman --noconfirm --needed -S ${XORG_XINIT}"

            # Install WM
            _info "Installing ${DESKTOP,,} window manager"
            _chroot "pacman --noconfirm --needed -S ${!DESKTOP}"
            ;;
    esac
}

_configure_desktop_environment() {

    case ${DESKTOP} in
        GNOME|KDE|MATE|XFCE4|LXDE|LXQT|DEEPIN|BUDGIE|CINNAMON|ENLIGHTENMENT)

            # Keyboard layout
            _info "Setting keyboard layout to ${KEYMAP^^}"
            wget ${URL}/conf/00-keyboard.conf
            sed -i -e "s/keymap_code/${KEYMAP}/g" 00-keyboard.conf
            mv -v 00-keyboard.conf /mnt/etc/X11/xorg.conf.d/
            ;;

        AWESOME|I3|XMONAD|BSPWM|HERBSTLUFTWM)

            # start WM with xinit
            _info "Setting ${DESKTOP,,} xinit start command"
            _chroot "cp -v /etc/X11/xinit/xinitrc /home/${USER_NAME}/.xinitrc"
            echo "exec ${DESKTOP,,}" >> /mnt/home/${USER_NAME}/.xinitrc
            ;;
    esac
}

# archboot by grm34 under Apache License 2.0
# ============================================================================
