#!/bin/bash

#                 DESKTOP ENVIRONMENT / WINDOW MANAGER
# ============================================================================
# Here we install desktop environment (or WM) with the required packages
# such as display server, fonts (to prevent issues in gtk apps on
# some DE), <terminator> and <numlockx> (to get numlock on bootup).
# To prevent password issues on the login screen of the display manager
# caused by wrong keyboard layout, we add keyboard.conf to xorg settings.
#
# All steps are described in the official documentation:
#
#   https://wiki.archlinux.org/index.php/Desktop_environment
#   https://wiki.archlinux.org/index.php/Window_manager
# ============================================================================

_install_desktop_environment() {

    # Xorg
    _info "Installing xorg server"
    _chroot "pacman --noconfirm --needed -S ${XORG}"
    case ${DESKTOP} in
        AWESOME|I3|XMONAD|BSPWM|HERBSTLUFTWM)
            _chroot "pacman --noconfirm --needed -S ${XORG_XINIT}"
            ;;
    esac

    # Fonts
    _info "Installing fonts"
    _chroot "pacman --noconfirm --needed -S ${FONTS}"

    # Numlock
    _info "Installing numlock"
    _chroot "pacman --noconfirm --needed -S ${NUMLOCK}"

    # Terminal
    _info "Installing terminal"
    _chroot "pacman --noconfirm --needed -S ${TERMINAL}"

    # Desktop Environment / Window Manager
    _info "Installing ${DESKTOP,,}"
    _chroot "pacman --noconfirm --needed -S ${!DESKTOP}"
}

_configure_desktop_environment() {

    # Keyboard layout
    _info "Setting keyboard layout to ${KEYMAP^^}"
    wget ${URL}/conf/00-keyboard.conf
    sed -i -e "s/keymap_code/${KEYMAP}/g" 00-keyboard.conf
    mv -v 00-keyboard.conf /mnt/etc/X11/xorg.conf.d/

    # Start WM with xinit
    case ${DESKTOP} in
        AWESOME|I3|XMONAD|BSPWM|HERBSTLUFTWM)
            _info "Setting ${DESKTOP,,} start command"
            _chroot "cp -v /etc/X11/xinit/xinitrc /home/${USER_NAME}/.xinitrc"
            echo "exec ${DESKTOP,,}" >> /mnt/home/${USER_NAME}/.xinitrc
            ;;
    esac
}

# archboot by grm34 under Apache License 2.0
# ============================================================================
