#!/bin/bash

_display_manager() {

    # GDM > Gnome
    if [[ ${desktop} == "gnome" ]]; then
        _info "Enabling GDM"
        wget ${_url}/conf/xprofile
        mv xprofile /mnt/etc/xprofile
        _chroot "systemctl enable gdm"

    # SDDM > Kde
    elif [[ ${desktop} == "kde" ]]; then
        _info "Enabling SDDM"
        sed -i -e "s/Numlock=none/Numlock=on/g" /mnt/etc/sddm.conf
        _chroot "systemctl enable sddm"

    # LIGHTDM > Deepin
    elif [[ ${desktop} == "deepin" ]]; then
        _info "Enabling LightDM"
        default_session="#greeter-session=example-gtk-gnome"
        session="greeter-session=lightdm-deepin-greeter"
        numlock="greeter-setup-script=/usr/bin/numlockx on"
        sed -i -e "s|${default-session}|${session}|g" \
        /mnt/etc/lightdm/lightdm.conf
        sed -i -e "s|#greeter-setup-script=|${numlock}|g" \
        /mnt/etc/lightdm/lightdm.conf
        _chroot "systemctl enable lightdm"

    # LXDM
    else
        _info "Enabling LXDM"
        default_session="# session=/usr/bin/startlxde"

        # Cinnamon / Mate
        if [[ ${desktop} == "cinnamon" || ${desktop} == "mate" ]]; then
            session="session=/usr/bin/${desktop}-session"


        # Enlightenment
        elif [[ ${desktop} == "enlightenment" ]]; then
            session="session=/usr/bin/enlightenment_start"

        # Budgie
        elif [[ ${desktop} == "budgie" ]]; then
            session="session=/usr/bin/budgie-desktop"

        # Xfce / Lxde / Lxqt
        else
            session="session=/usr/bin/start${desktop}"
        fi

        # Configure settings
        sed -i -e "s/${default_session}/${session}/g" /mnt/etc/lxdm/lxdm.conf
        sed -i -e "s/# numlock=0/numlock=1/g" /mnt/etc/lxdm/lxdm.conf
        sed -i -e "s/white=/white=${USER_name}/g" /mnt/etc/lxdm/lxdm.conf
        sed -i -e "s/black=/black=root/g" /mnt/etc/lxdm/lxdm.conf
        _chroot "systemctl enable lxdm"
    fi
}
