#!/bin/bash

#                           DISPLAY MANAGER
# ============================================================================
# Here we install and configure display manager to properly start DE/WM.
#
#   Default settings:
#
#     GDM........: Gnome
#     SDDM.......: Kde
#     LIGHTDM....: Deepin / Budgie / Cinnamon / Mate
#     LXDM.......: Xfce4 / Lxde / Lxqt / Enlightenment
#     XDM........: Awesome / i3 / Xmonad
#
# All steps are described in the official documentation:
#
#   https://wiki.archlinux.org/index.php/Display_manager
# ============================================================================

_install_display_manager() {

    ### Install Display Manager
    _info "${MSG_INSTALL_DISPLAY} (${DISPLAY_MAN,,})"
    DISPLAY_APPS=("${!DISPLAY_MAN}")

    if [[ ${DISPLAY_MAN} == "LIGHTDM" && \
${GREETER} != "DEEPIN_GREETER" ]]; then DISPLAY_APPS+=("${!GREETER}"); fi

    _chroot "pacman --noconfirm --needed -S ${DISPLAY_APPS[*]}"

    ### Enable Display Manager
    if [[ ${DISPLAY_MAN} == "XDM" ]]; then
        _chroot "systemctl enable ${DISPLAY_MAN,,}-archlinux"
    else
        _chroot "systemctl enable ${DISPLAY_MAN,,}"
    fi
    echo "-> ${MSG_DONE}"

    ### Start command of each DE or WM
    case ${DESKTOP} in
        GNOME|MATE|CINNAMON) SESSION="/usr/bin/${DESKTOP,,}-session";;
        KDE|XFCE4|LXDE|LXQT) SESSION="/usr/bin/start${DESKTOP,,}";;
        ENLIGHTENMENT) SESSION="/usr/bin/enlightenment_start";;
        BUDGIE) SESSION="/usr/bin/budgie-desktop";;
        DEEPIN) SESSION="/usr/bin/startdde";;
        *) SESSION="/home/${USER_NAME}/.xinitrc"
    esac

    ### Configure display manager
    if [[ ${DISPLAY_MAN} != "LIGHTDM" ]]; then
        _info "${MSG_SET_DISPLAY} (${DISPLAY_MAN,,})"
    fi

    ### GDM
    if [[ ${DISPLAY_MAN} == "GDM" ]]; then
        echo "-> ${MSG_DOWNLOADING} xprofile..."
        _wget "${URL}/src/conf/xprofile" && echo
        mv -v xprofile /mnt/etc/xprofile
        echo "-> ${MSG_DONE}"

    ### LIGHTDM
    elif [[ ${DISPLAY_MAN} == "LIGHTDM" ]]; then

        # Define Greeter Session
        case ${GREETER} in
            GTK_GREETER) LIGHTDM_SESSION="lightdm-gtk-greeter";;
            PANTHEON_GREETER) LIGHTDM_SESSION="io.elementary.greeter";;
            DEEPIN_GREETER) LIGHTDM_SESSION="lightdm-deepin-greeter";;
            *) LIGHTDM_SESSION="lightdm-webkit2-greeter"
        esac

        # Configure Greeter
        _info "${MSG_SET_GREETER}"
        DEFAULT_SESSION="#greeter-session=example-gtk-gnome"
        SESSION="greeter-session=${LIGHTDM_SESSION}"
        NUMON="greeter-setup-script=/usr/bin/numlockx on"
        NUMOFF="#greeter-setup-script="

        sed -i -e \
"s|${DEFAULT_SESSION}|${SESSION}|g" /mnt/etc/lightdm/lightdm.conf

        sed -i -e \
"s|${NUMOFF}|${NUMON}|g" /mnt/etc/lightdm/lightdm.conf

        echo "-> ${MSG_DONE}"

    ### SDDM
    elif [[ ${DISPLAY_MAN} == "SDDM" ]]; then
        _chroot "sddm --example-config > /etc/sddm.conf"
        sed -i -e "s|Session=|Session=${SESSION}|g" /mnt/etc/sddm.conf
        sed -i -e "s/Numlock=none/Numlock=on/g" /mnt/etc/sddm.conf
        echo "-> ${MSG_DONE}"

    ### LXDM
    elif [[ ${DISPLAY_MAN} == "LXDM" ]]; then
        DEFAULT_SESSION="# session=/usr/bin/startlxde"

        sed -i -e \
"s|${DEFAULT_SESSION}|session=${SESSION}|g" /mnt/etc/lxdm/lxdm.conf

        sed -i -e "s/# numlock=0/numlock=1/g" /mnt/etc/lxdm/lxdm.conf

        sed -i -e \
"s/white=/white=${USER_NAME}/g" /mnt/etc/lxdm/lxdm.conf

        sed -i -e "s/black=/black=root/g" /mnt/etc/lxdm/lxdm.conf
        echo "-> ${MSG_DONE}"

    ### XDM
    elif [[ ${DISPLAY_MAN} == "XDM" ]]; then
        echo "${SESSION}" > "/mnt/home/${USER_NAME}/.xsession"
        chmod 770 "/mnt/home/${USER_NAME}/.xsession"
        echo "-> ${MSG_DONE}"
    fi
}

# archboot - Arch Linux Installer by grm34 under Apache License 2.0
# ============================================================================
