#!/bin/bash

_display_manager() {

    # Install Display Manager
    _info "Installing ${display_man}"
    install_display="_${display_man}"
    _chroot "pacman --noconfirm -S ${!install_display}; "
    _chroot "systemctl enable ${display_man}"

    # Session start command
    case ${desktop} in
        gnome|mate|cinnamon) session="/usr/bin/${desktop}-session";;
        kde|xfce4|lxde|lxqt) session="/usr/bin/start${desktop}";;
        enlightenment) session="/usr/bin/enlightenment_start";;
        budgie) session="/usr/bin/budgie-desktop";;
        deepin) session="/usr/bin/startdde";;
    esac

    # GDM
    if [[ ${display_man} == "gdm" ]]; then
        wget ${_url}/conf/xprofile
        mv xprofile /mnt/etc/xprofile

    # LIGHTDM
    elif [[ ${display_man} == "lightdm" ]]; then

        # Select Greeter
        if [[ ${desktop} == "deepin"]]; then
            greeter="deepin"
        elif [[ ${desktop} == "kde"]]; then
            greeter="kde"
        else
            greeter="gtk"
        fi

        default="#greeter-session=example-gtk-gnome"
        session="greeter-session=lightdm-${greeter}-greeter"
        num_on="greeter-setup-script=/usr/bin/numlockx on"
        num_off="#greeter-setup-script="
        sed -i -e "s|${default}|${session}|g" /mnt/etc/lightdm/lightdm.conf
        sed -i -e "s|${num_off}|${num_on}|g" /mnt/etc/lightdm/lightdm.conf

    # SDDM
    elif [[ ${display_man} == "sddm" ]]; then
        _chroot "sddm --example-config > /etc/sddm.conf"
        sed -i -e "s|Session=|Session=${session}|g" /mnt/etc/lxdm/lxdm.conf
        sed -i -e "s/Numlock=none/Numlock=on/g" /mnt/etc/sddm.conf

    # LXDM
    elif [[ ${display_man} == "lxdm" ]]; then
        default="# session=/usr/bin/startlxde"
        sed -i -e "s|${default}|session=${session}|g" /mnt/etc/lxdm/lxdm.conf
        sed -i -e "s/# numlock=0/numlock=1/g" /mnt/etc/lxdm/lxdm.conf
        sed -i -e "s/white=/white=${USER_name}/g" /mnt/etc/lxdm/lxdm.conf
        sed -i -e "s/black=/black=root/g" /mnt/etc/lxdm/lxdm.conf

    # XDM
    elif [[ ${display_man} == "xdm" ]]; then
        echo ${session} > /mnt/home/${USER_name}/.xsession
        chmod 700 /mnt/home/${USER_name}/.xsession
    fi
}
