#!/bin/bash

#                        FIRMWARE DETECTION
# ============================================================================
# Here we detect if system is running on UEFI or BIOS firmware to properly
# set partition order, type, table, filesystem and to store them.
# ============================================================================

_firmware() {

    _info "Firmware detection"

    # UEFI Firmware
    if [ -d /sys/firmware/efi/efivars ]; then
        export FIRMWARE="UEFI"
        export PART_TABLE="GPT"
        export PART_CODE="g"
        export PART_TYPE=""
        export BOOT_FILESYSTEM="fat -F32"
        _note "UEFI firmware detected!"

    # BIOS Firmware
    else
        export FIRMWARE="BIOS"
        export PART_TABLE="MBR"
        export PART_CODE="o"
        export PART_TYPE="p\n"
        export BOOT_FILESYSTEM="ext4"
        _note "BIOS firmware detected!"
    fi
}

# archboot by grm34 under Apache License 2.0
# ============================================================================
