#!/bin/bash

# FIRMWARE DETECTION & MIRRORLIST SORTING
# ============================================================================
# Here we detect if system is running on UEFI or BIOS firmware to properly
# define partitions order, type, table and filesystem.
# More informations on partitioning are available in the official
# documentation: https://wiki.archlinux.org/index.php/Partitioning

_firmware() {

    # Firmware Detection
    _info "Firmware detection"
    if [ -d /sys/firmware/efi/efivars ]; then
        export FIRMWARE="UEFI"
        export part_table="GPT"
        export part_code="g"
        export part_type=""
        export boot_filesystem="fat -F32"
        _note "UEFI firmware detected."
    else
        FIRMWARE="BIOS"
        export part_table="MBR"
        export part_code="o"
        export part_type="p\n"
        export boot_filesystem="ext4"
        _note "BIOS firmware detected."
    fi
}

_mirrorlist() {

    # Automatic mirrorlist sorting according user's country
    _info "Setting country code"
    country=$(curl -s ipinfo.io/ | grep "country" | grep -o '[A-Z][^ ]')
    if [[ $country =~ ^[A-Z]{2}+$ ]]; then
        _info "Updating ${country} mirrorlist"
        mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
        curl -s \
"https://www.archlinux.org/mirrorlist/?country=${country}\
&use_mirror_status=on" | sed -e 's/^#Server/Server/' -e '/^#/d' \
> /etc/pacman.d/mirrorlist
        cat /etc/pacman.d/mirrorlist.backup >> /etc/pacman.d/mirrorlist
        rm /etc/pacman.d/mirrorlist.backup
    fi
}
