#!/bin/bash

#                        GPU CONTROLLER DRIVER
# ============================================================================
# Here we scan for 3D GPU Controller to install appropriate driver with
# OpenGL and Hardware Acceleration (if currently supported). We don't use
# FOR loop (wich can shorten the code) to prevent issues in case of dual
# GPU and to ensure the integrated will not be installed as principal GPU.
#
# All steps are described in the official documentation:
#
#   https://wiki.archlinux.org/index.php/Xorg#Driver_installation
# ============================================================================

_get_gpu_driver() {

    _info "${MSG_GET_GPU}"

    ### NVIDIA
    NVIDIA_CARD=$( lspci | grep -e VGA -e 3D | grep -ie nvidia )

    if [[ ${NVIDIA_CARD} ]]; then
        _note "${NVIDIA_CARD##*: } ${MSG_DETECTED}"
        _confirm "${MSG_CONFIRM_INSTALL_GPUPRO}"
        case ${CONFIRM} in

            # Proprietary drivers
            y|Y|yes|Yes|YES)
                case ${KERNEL} in
                    LTS_KERNEL) export GPU_DRIVER="NVIDIA_LTS";;
                    HARDENED_KERNEL|ZEN_KERNEL)
                        export GPU_DRIVER="NVIDIA_DKMS";;
                    DEFAULT_KERNEL) export GPU_DRIVER="NVIDIA_DRIVER"
                esac;;

            # Opensource drivers
            *) export GPU_DRIVER="NOUVEAU_DRIVER"
        esac
    else

        ### AMD / ATI
        AMD_CARD=$( lspci | grep -e VGA -e 3D | grep -e ATI -e AMD )

        if [[ ${AMD_CARD} ]]; then
            _note "${AMD_CARD##*: } ${MSG_DETECTED}"
            export GPU_DRIVER="AMD_DRIVER"
        else

            ### INTEL
            INTEL_CARD=$( lspci | grep -e VGA -e 3D | grep -i intel )

            if [[ ${INTEL_CARD} ]]; then
                _note "${INTEL_CARD##*: } ${MSG_DETECTED}"
                export GPU_DRIVER="INTEL_DRIVER"

            ### DEFAULT
            else
                _note "${MSG_GPU_FALSE}"
                export GPU_DRIVER="DEFAULT_DRIVER"
            fi
        fi
    fi

    ### OpenGL and Hardware Video Acceleration
    if [[ ${GPU_DRIVER} != "DEFAULT_DRIVER" ]]; then
        _confirm "${MSG_CONFIRM_HARDVIDEO}"

        case ${CONFIRM} in y|Y|yes|Yes|YES)
            export OPENGL="OPENGL_${GPU_DRIVER/_*/}"
            export HARDVIDEO="HARDVIDEO_${GPU_DRIVER/_*/}"
        esac
    fi
}

_install_gpu_driver() {

    ### Install GPU driver
    _info "${MSG_INSTALL_GPU_DRIVER}"
    _chroot "pacman --noconfirm --needed -S ${!GPU_DRIVER}"
    echo "-> ${MSG_DONE}"

    ### Install openGL and hardware video acceleration
    if [[ ${GPU_DRIVER} != "DEFAULT_DRIVER" && ${HARDVIDEO} ]]; then
        _info "${MSG_INSTALL_HARDVIDEO}"

        _chroot "pacman --noconfirm --needed -S \
${!OPENGL} ${!HARDVIDEO} ${HARDVIDEO_UTILS}"

        echo "-> ${MSG_DONE}"
    fi
}

# archboot - Arch Linux Installer by grm34 under Apache License 2.0
# ============================================================================
