#!/bin/bash

#                   MOUNT PARTITIONS & ACTIVATE SWAP
# ============================================================================
# Here we mount all previously created partitions and activate swap.
# All steps are described in the official documentation:
# https://wiki.archlinux.org/index.php/File_systems#Mount_a_file_system
# ============================================================================

_mount_partitions() {

    _info "Mounting partitions and activating swap"

    # Mount system on /mnt
    _check mount ${SYSTEM_MOUNTPOINT} /mnt

    # Create boot and home folders
    _check mkdir /mnt/{boot,home}

    # Mount UEFI Boot on /mnt/boot/efi
    if [[ ${FIRMWARE} == "UEFI" ]]; then
        _check mkdir -p /mnt/boot/efi/EFI
        _check mount -t vfat ${BOOT_MOUNTPOINT} /mnt/boot/efi

    # Mount BIOS Boot on /mnt/boot
    else
        _check mount ${BOOT_MOUNTPOINT} /mnt/boot
    fi

    # Activate swap
    _check swapon ${SWAP_MOUNTPOINT}

    # Mount home on /mnt/home
    _check mount ${HOME_MOUNTPOINT} /mnt/home
}

# archboot by grm34 under Apache License 2.0
# ============================================================================
