#!/bin/bash

#                   MOUNT PARTITIONS & ACTIVATE SWAP
# ============================================================================
# Here we mount all previously created partitions and we activate swap.
#
# All steps are described in the official documentation:
#
#   https://wiki.archlinux.org/index.php/File_systems#Mount_a_file_system
# ============================================================================

_mount_partitions() {

    _info "${MSG_MOUNT_PARTITIONS}"

    ### Mount system > /mnt
    _check mount -v "${ROOT_PARTITION}" /mnt

    ### Create boot and home folders
    _check mkdir -v /mnt/{boot,home}

    ### Mount boot > /mnt/boot
    _check mount -v "${MOUNT_TYPE}${BOOT_PARTITION}" /mnt/boot

    ### Activate swap
    if [[ ${SWAP_PARTITION} ]]; then
        _check swapon -v "${SWAP_PARTITION}"
    fi

    ### Mount home > /mnt/home
    if [[ ${HOME_PARTITION} ]]; then
        _check mount -v "${HOME_PARTITION}" /mnt/home
    fi
}

# archboot - Arch Linux Installer by grm34 under Apache License 2.0
# ============================================================================
