#!/bin/bash

_scan_vga_controller() {

	_info "Scanning VGA Controller"
	vga_number=$(lspci | grep -e VGA -e 3D | wc -l)

	# DUAL VGA CONTROLLER
	if [[ ${vga_number} -ge "2" ]]; then

		# Check if Intel & Nvidia to install Bumblebee
		lspci | grep -e VGA -e 3D | grep -ie nvidia | grep -i intel
		if [[ $? -eq 0 ]]; then
			_note "Nvidia + Intel - System compatible to install Bumblebee."
			_confirm "Use Nvidia proprietary driver instead of open source?"
		    if [[ ${confirm} == "y" ]]; then
		        export vga_driver="bumblebee_nvidia"
		        export openGL_x64="openGL_x64_nvidia"
				export openGL_x86="openGL_x86_nvidia"
				export hard_video="hard_video_nvidia"

		    else
		    	export vga_driver="bumblebee_nouveau"
		    	export openGL_x64="openGL_x64_nouveau"
				export openGL_x86="openGL_x86_nouveau"
				export hard_video="hard_video_nouveau"
		    fi
		    unset confirm
		fi

	# SINGLE VGA CONTROLLER
	else

		# NVIDIA
		nvidia_card=$(lspci | grep -e VGA -e 3D | grep -ie nvidia)
		if [[ $? -eq 0 ]]; then
			_note "${nvidia_card##*: } detected."
			_confirm "Use Nvidia proprietary driver instead of open source?"
		    if [[ ${confirm} == "y" ]]; then
		        export vga_driver="nvidia"
		        export openGL_x64="openGL_x64_nvidia"
				export openGL_x86="openGL_x86_nvidia"
				export hard_video="hard_video_nvidia"
		    else
		    	export vga_driver="nouveau"
		    	export openGL_x64="openGL_x64_nouveau"
				export openGL_x86="openGL_x86_nouveau"
				export hard_video="hard_video_nouveau"
		    fi
		    unset confirm
		else

			# AMD / ATI
			amd_card=$(lspci | grep -e VGA -e 3D | grep -e ATI -e AMD)
			if [[ $? -eq 0 ]]; then
				_note "${amd_card##*: } detected."
				_confirm "Use ATI proprietary driver instead of open source?"
			    export vga_driver="amd"
			    export openGL_x64="openGL_x64_amd"
				export openGL_x86="openGL_x86_amd"
				export hard_video="hard_video_amd"

			else

				# INTEL
				intel_card=$(lspci | grep -e VGA -e 3D | grep -i intel)
				if [[ $? -eq 0 ]]; then
					_note "${intel_card##*: } detected."
					export vga_driver="intel"
					export openGL_x64="openGL_x64_intel"
					export openGL_x86="openGL_x86_intel"
					export hard_video="hard_video_intel"

				# DEFAULT
				else
					_note "Controller not found, default driver will be used."
					export vga_driver="default"
				fi
			fi
		fi
	fi
}
