#!/bin/bash

_yaourt() {

    # Setting pacman.conf
    _info "Setting pacman.conf"
    _chroot "wget $_url/conf/pacman.conf
    mv pacman.conf /etc/pacman.conf"

   # Setting Mirrorlist
    _info "Setting mirrorlist"
    _chroot "reflector -c FR --sort rate --save /etc/pacman.d/mirrorlist"

    # Install yaourt
    _info "Installing yaourt"
    _chroot "pacman --noconfirm -Syu $_yaourtapps"
}
