#!/bin/bash

# Display Server
export xorg="xorg xorg-server xorg-apps xorg-drivers"

#
# DESKTOP ENVIRONMENT
#

# Gnome
export _gnome="gnome gnome-extra"

# Kde
export _kde="plasma kde-applications"

# Lxde
export _lxde="lxde"

# Xfce
export _xfce4="xfce4 xfce4-goodies lxdm"

# Deepin
export _deepin="deepin deepin-extra"

# Cinnamon
#export _cinnamon="cinnamon"

# Budgie
#export _budgie="budgie-desktop"

# Enlightenment
#export _enlightenment="enlightenment terminology"

# Mate
#export _mate="mate mate-extra"

# Lxqt
#export _lxqt="lxqt"
