#!/bin/bash

#                     DESKTOP ENVIRONMENT PACKAGES
# ============================================================================

# Gnome
export _gnome="gnome gnome-extra"

# Kde
export _kde="plasma kde-applications"

# Lxde
export _lxde="lxde"

# Xfce
export _xfce4="xfce4 xfce4-goodies"

# Deepin
export _deepin="deepin deepin-extra"

# Cinnamon
export _cinnamon="cinnamon"

# Budgie
export _budgie="budgie-desktop"

# Enlightenment
export _enlightenment="enlightenment"

# Mate
export _mate="mate mate-extra"

# Lxqt
export _lxqt="lxqt"

#                         REQUIRED PACKAGES
# ============================================================================

# Xorg
export _xorg="xorg-server"

# Fonts
export _fonts="xorg-fonts-type1 ttf-dejavu font-bh-ttf \
font-bitstream-speedo gsfonts sdl_ttf ttf-bitstream-vera \
ttf-liberation ttf-freefont ttf-arphic-uming ttf-baekmuk"

# Numlock
export _numlock="numlockx"

# Terminal
export _term="terminator"

# archboot by grm34 under Apache License 2.0
# ============================================================================
