#!/bin/bash

#                     DESKTOP ENVIRONMENT PACKAGES
# ============================================================================

# Gnome
export GNOME="gnome gnome-extra"

# Kde
export KDE="plasma kde-applications"

# Lxde
export LXDE="lxde"

# Xfce
export XFCE4="xfce4 xfce4-goodies"

# Deepin
export DEEPIN="deepin deepin-extra"

# Cinnamon
export CINNAMON="cinnamon"

# Budgie
export BUDGIE="budgie-desktop"

# Enlightenment
export ENLIGHTENMENT="enlightenment"

# Mate
export MATE="mate mate-extra"

# Lxqt
export LXQT="lxqt"

#                       WINDOW MANAGER PACKAGES
# ============================================================================

# awesome
export AWESOME="awesome"

# i3
export I3="i3-wm"

# xmonad
export XMONAD="xmonad xmonad-contrib"

# bspwm
export BSPWM="bspwm"

# herbstluftwm
export HERBSTLUFTWM="herbstluftwm"

#                         REQUIRED PACKAGES
# ============================================================================

# Xorg
export XORG="xorg-server"
export XORG_XINIT="xorg-xinit"

# Fonts
export FONTS="xorg-fonts-type1 ttf-dejavu font-bh-ttf \
font-bitstream-speedo gsfonts sdl_ttf ttf-bitstream-vera \
ttf-liberation ttf-freefont ttf-arphic-uming ttf-baekmuk"

# Numlock
export NUMLOCK="numlockx"

# Terminal
export TERMINAL="terminator"

# archboot by grm34 under Apache License 2.0
# ============================================================================
