#!/bin/bash

#                       DISPLAY MANAGER PACKAGES
# ============================================================================

# GDM
export _gdm="gdm"

# LightDM
export _lightdm="lightdm"

# SDDM
export _sddm="sddm"

# LXDM
export _lxdm="lxdm"

# XDM
export _xdm="xorg-xdm"

# archboot by grm34 under Apache v2.0 License.
# ============================================================================
