#!/bin/bash

#                       DISPLAY MANAGER PACKAGES
# ============================================================================

# GDM
export GDM="gdm"

# SDDM
export SDDM="sddm"

# LXDM
export LXDM="lxdm"

# XDM
export XDM="xorg-xdm xdm-archlinux"

# LightDM
export LIGHTDM="lightdm"

# LightDM Greeter
export GTK_GREETER="lightdm-gtk-greeter"
export PANTHEON_GREETER="lightdm-pantheon-greeter"
export WEBKIT_GREETER="lightdm-webkit2-greeter"
export LITARVAN_GREETER="lightdm-webkit-theme-litarvan"

# archboot - Arch Linux Installer by grm34 under Apache License 2.0
# ============================================================================
