#!/bin/bash

# Arch Linux
export _arch="base base-devel"

# Microcode (in case of Intel CPU)
export _intel="intel-ucode"

# Network
export _netapps="ntp networkmanager wget nmap rp-pppoe dhclient \
iw wpa_supplicant wireless_tools git"

# Bootloader
export _bootapps="grub os-prober gptfdisk efibootmgr"

# Arch User Repository (in case of AUR support)
export _yaourtapps="yaourt customizepkg"

# Numlock (in case of Desktop Environment)
export _numlock="numlockx"

# Fonts (in case of Desktop Environment)
export _fonts="xorg-fonts-type1 ttf-dejavu artwiz-fonts font-bh-ttf \
font-bitstream-speedo gsfonts sdl_ttf ttf-bitstream-vera ttf-cheapskate \
ttf-liberation ttf-freefont ttf-arphic-uming ttf-baekmuk"

# Terminal (in case of Desktop Environment)
export _term="terminator"
