#!/bin/bash

#                         ARCH LINUX PACKAGES
# ============================================================================

# Arch Linux
export ARCH="base base-devel linux-firmware"

# Kernel (the one you like)
export DEFAULT_KERNEL="linux"
export HARDENED_KERNEL="linux-hardened"
export LTS_KERNEL="linux-lts"
export ZEN_KERNEL="linux-zen"

# Microcode (Intel CPU only)
export INTEL_UCODE="intel-ucode"

# Network
export NETAPPS="ntp networkmanager wget nmap rp-pppoe dhclient \
iw wpa_supplicant wireless_tools git"

# Bootloader (BIOS only)
export BOOTAPPS="grub os-prober gptfdisk efibootmgr"

# archboot by grm34 under Apache License 2.0
# ============================================================================
