#!/bin/bash

# DEFAULT
# ============================================================================

# Default Driver
export _default="xf86-video-vesa"

# INTEL
# ============================================================================

# Driver Intel
export _intel="xf86-video-intel"

# OpenGL Intel (open source)
export _openGL_intel="mesa"
export _hard_video_intel="vulkan-intel libva-intel-driver libvdpau-va-gl"

# ATI/AMD
# ============================================================================

# Driver AMD (open source)
export _amd="xf86-video-ati xf86-video-amdgpu"

# OpenGL Intel
export _openGL_amd="mesa"
export _hard_video_amd="vulkan-radeon libva-mesa-driver mesa-vdpau"

# NVIDIA
# ============================================================================

# Driver Nouveau (open source)
export _nouveau="xf86-video-nouveau"

# Driver Nvidia (proprietary)
export _nvidia="nvidia nvidia-settings"

# OpenGL Nouveau (open source)
export _openGL_nouveau="mesa"
export _hard_video_nouveau="libva-vdpau-driver mesa-vdpau"

# OpenGL Nvidia (proprietary)
export _openGL_nvidia="nvidia-utils"
export _hard_video_nvidia="libva-vdpau-driver"

# BUMBLEBEE
# ============================================================================

# Driver Bumblebee (open source)
export _bumblebee_nvidia="bumblebee xf86-video-intel xf86-video-nouveau"

# Driver Bumblebee (proprietary)
export _bumblebee_nouveau="bumblebee xf86-video-intel xf86-video-nvidia"
