
### ARCHBOOT ###

export VISUAL='nano'
alias ²system='inxi -F -M'
alias ²install='yaourt -S'
alias ²delete='yaourt -Rcsn'
alias ²update='yaourt -Syyua'
alias ²clean='yaourt -Scc'
alias ²purge='yaourt -Qdt'
alias ²verif='yaourt -Qqk'
alias ²pacnew='yaourt -C'
alias ²search='yaourt -s'
alias ²mirrorlist='sudo reflector -c FR --sort rate --save /etc/pacman.d/mirrorlist'
