#!/bin/bash

#######################
### GLOBAL PACKAGES ###
#######################

# Intel Microcode
export _intel="intel-ucode"

# File system
export _file_system="gamin gvfs gvfs-mtp gvfs-nfs gvfs-afc gparted ntfs-3g \
dosfstools exfat-utils file-roller ifuse fuseiso unrar"

# Firefox
export _firefox="firefox firefox-i18n-fr hunspell-fr"

# Flash
export _flash="flashplugin"

# Java
export _java="jre8-openjdk"

# Libreoffice
export _libreoffice="libreoffice libreoffice-fr"

# Gimp
export _gimp="gimp"

# Cups
export _cups="cups cups-pdf ghostscript gutenprint"

# Sane
export _sane="sane simple-scan"

###########################
### DESKTOP ENVIRONMENT ###
###########################

# Gnome Desktop
export _gnome="gnome gnome-extra"

# KDE Desktop
export _kde="plasma kde-applications kde-l10n-fr aspell-fr \
libappindicator-gtk2 libappindicator-gtk3 sni-qt \
lib32-libappindicator-gtk2 lib32-libappindicator-gtk2 \
kde-gtk-config oxygen-gtk2 oxygen-kde4 qtcurve-gtk2 qtcurve-qt5"

# Lxde Desktop
export _lxde="lxde"

# Xfce Desktop
export _xfce="xfce4 xfce4-goodies"

#######################
### DISPLAY MANAGER ###
#######################

# Sddm Display Manager
export _sddm="sddm sddm-kcm"

# Lxdm Display Manager
export _lxdm="lxdm"

#####################
### XFCE PACKAGES ###
#####################

# Fonts
export _fonts="xorg-fonts-type1 ttf-dejavu artwiz-fonts font-bh-ttf \
font-bitstream-speedo gsfonts sdl_ttf ttf-bitstream-vera \
ttf-cheapskate ttf-liberation ttf-freefont ttf-arphic-uming ttf-baekmuk"

# Multimedia
export _multimedia="pulseaudio pulseaudio-alsa pavucontrol \
mplayer parole vlc guvcview mediainfo-gui ffmpegthumbnailer"

# Docky
export _docky="docky"

# Accessories
export _accessories="gnome-calculator fbreader mupdf"

# Network Applet
export _network_applet="network-manager-applet"
