#!/bin/bash

_install_DE() {

    # File System
    _info "Installing File System"
    _chroot "pacman --noconfirm -S ${_file_system}"

    # Fonts
    _info "Installing Fonts"
    _chroot "pacman --noconfirm -S ${_fonts}"

    # GPU Driver
    _info "Installing VGA Driver"
    _chroot "pacman --noconfirm -S ${GPU_driver}"

    # Desktop Environment
    _info "Installing $desktop"
    user_desktop="_$desktop"
    _chroot "pacman --noconfirm -S ${!user_desktop}"
 }

_display_manager() {

    # XFCE or LXDE > LXDM
    if [[ ${desktop} == "xfce" || ${desktop} == "lxde" ]]
    then
        _info "Enabling LXDM"
        _chroot "wget $_url/conf/lxdm_${desktop}.conf
        mv lxdm_${desktop}.conf /etc/lxdm/lxdm.conf
        systemctl enable lxdm"

    # GNOME > GDM
    elif [[ ${desktop} == "gnome" ]]
    then
        _info "Enabling GDM"
        _chroot "systemctl enable gdm"

    # KDE > SDDM
    elif [[ ${desktop} == "kde" ]]
    then
        _info "Enabling SDDM"
        _chroot "systemctl enable sddm"

    # DEEPIN > LIGHTDM
    elif [[ ${desktop} == "deepin" ]]
    then
        _info "Enabling LightDM"
        _chroot "wget $_url/conf/lightdm.conf
        mv lightdm.conf /etc/lightdm/lightdm.conf
        systemctl enable lightdm"
    fi
}

_DE_settings() {

    # Keyboard layout
    _info "Setting keyboard layout"
    _chroot "wget ${_url}/conf/00-keyboard.conf
    sed -i -e 's/keymap_code/$keymap_code/g' 00-keyboard.conf
    mv 00-keyboard.conf /etc/X11/xorg.conf.d/"

    # Groups
    _info "Add ${USER_name} to all groups"
    group_list=$(cut -d: -f1 /mnt/etc/group)
    for group in ${group_list}
    do
        _chroot "usermod -aG ${group} ${USER_name}"
    done
}
