#!/bin/bash

_gpu() {

    # GPU Drivers
    _info "GPU detection"
    GPU_driver="xf86-video-vesa"
    Accel_driver="mesa lib32-mesa mesa-vdpau lib32-mesa-vdpau mesa-libgl lib32-mesa-libgl"

    # Intel GPU
    lspci | grep "VGA" | grep "Intel" >/dev/null 2>&1
    if [[ $? -eq 0 ]]
    then
        _note "found INTEL GPU"
        export GPU_driver="xf86-video-intel vulkan-intel libva-intel-driver ${Accel_driver}"
    fi

    # ATI GPU
    lspci | grep "VGA" | grep "ATI" >/dev/null 2>&1
    if [[ $? -eq 0 ]]
    then
        _note "found ATI GPU"
        export GPU_driver="xf86-video-ati xf86-video-amdgpu ${Accel_driver}"
    fi

    # nVidia GPU
    lspci | grep "VGA" | grep "nVidia" >/dev/null 2>&1
    if [[ $? -eq 0 ]]
    then
        _note "found nVidia GPU"
        export GPU_driver="xf86-video-nouveau nouveau-dri ${Accel_driver}"
    fi
}
