#!/bin/bash

_base() {

    # Install Base System
    _info "Installing base system"
    yes '' | pacstrap /mnt base base-devel

    # Setting fstab
    _info "Setting fstab"
    genfstab -U -p /mnt >> /mnt/etc/fstab

    # root password
    _info "Setting root password"
    _chroot 'echo "root:${ROOT_passwd}" | chpasswd'

    # Setting TimeZone
    _info "Setting TimeZone"
    ln -sf /mnt/usr/share/zoneinfo/Europe/Paris /mnt/etc/localtime

    # Setting locale
    _info "Setting and generating locale"
    echo "fr_FR.UTF-8 UTF-8" >> /mnt/etc/locale.gen
    _chroot 'locale-gen; export LANG=fr_FR.UTF-8'
    echo "LANG=fr_FR.UTF-8" > /mnt/etc/locale.conf

    # Setting keyboard
    _info "Setting keyboard"
    echo "KEYMAP=fr-pc" > /mnt/etc/vconsole.conf

    # Setting Linux
    _info "Setting Linux environment"
    _chroot 'mkinitcpio -p linux'

    # Install Network
    _info "Installing network"
    _chroot 'pacman --noconfirm -S networkmanager wireless_tools \
        wpa_supplicant; systemctl enable NetworkManager.service'

    # Install required packages
    _info "Installing required packages"
    _chroot 'pacman --noconfirm -S wget reflector git inxi \
        htop nmap ntp numlockx'
}
