#!/bin/bash

_bootloader() {

    # Install Bootloader
    _info "Installing $FIRMWARE Bootloader"
    _chroot 'pacman --noconfirm -S grub os-prober gptfdisk efibootmgr'
    if [[ "$FIRMWARE" == "UEFI" ]]; then
        _chroot 'grub-install --target=x86_64-efi --efi-directory=/boot/efi \
            --bootloader-id=arch_grub --recheck'
    else
        _chroot 'grub-install --no-floppy --recheck /dev/$_disk'
    fi

    # Install Grub Themes
    _info "Installing Grub Themes"
    _chroot 'grub-mkconfig -o /boot/grub/grub.cfg'
    git clone git://github.com/Generator/Grub2-themes.git
    cp -r Grub2-themes/{Archlinux,Archxion} /mnt/boot/grub/themes/
    rm -r Grub2-themes
    sed -i -e "s/GRUB_GFXMODE=auto/GRUB_GFXMODE=1024x768/g" /mnt/etc/default/grub
    echo "GRUB_THEME=/boot/grub/themes/Archlinux/theme.txt" >> /mnt/etc/default/grub
    echo 'desktop-image: "background.png" >> /mnt/boot/grub/themes/Archlinux/theme.txt'
    _chroot 'grub-mkconfig -o /boot/grub/grub.cfg'
    wget https://raw.githubusercontent.com/grm34/archboot/master/img/background.png
    mv background.png /mnt/boot/grub/themes/Archlinux/
}
