#!/bin/bash

_install_desktop() {

    # Intel Microcode
    lscpu | grep "Intel" >/dev/null 2>&1
    if [[ $? -eq 0 ]]; then
        _info "Installing Intel CPU Microcode"
        _chroot 'pacman --noconfirm -S intel-ucode'
    fi

    # GPU Driver
    _info "Installing VGA Driver"
    _chroot 'pacman --noconfirm -S $GPU_driver'

    # File System
    _info "Installing File System"
    _chroot \
        'pacman --noconfirm -S gamin gvfs gvfs-mtp gvfs-nfs \
        gvfs-afc gparted ntfs-3g dosfstools exfat-utils \
        file-roller ifuse fuseiso unrar'

    # Gnome
    _info "Installing Gnome"
    _chroot 'pacman --noconfirm -S gnome gnome-extra'

    # Firefox
    _info "Installing Firefox"
    _chroot \
        'pacman --noconfirm -S firefox firefox-i18n-fr hunspell-fr flashplugin'

    # Java
    _info "Installing Java"
    _chroot 'pacman --noconfirm -S jre8-openjdk'

    # Libreoffice
    _info "Installing Libreoffice"
    _chroot 'pacman --noconfirm -S libreoffice libreoffice-fr'

    # Gimp
    _info "Installing Gimp"
    _chroot 'pacman --noconfirm -S gimp'

    # Cups
    _info "Installing Cups"
    _chroot \
        'pacman --noconfirm -S cups cups-pdf ghostscript \
        gutenprint sane simple-scan'
}

_desktop_settings() {

    # Keyboard layout
    _info "Setting keyboard layout"
    _chroot 'localectl --no-convert set-x11-keymap fr'

    # Themes & icons
    _info "Adding some themes & icons"
    _chroot \
        'wget https://raw.githubusercontent.com/grm34/archboot/master/data/gnome.tar.xz
        tar xf gnome.tar.xz -C /home/$USER_name/ && rm gnome.tar.xz'

    # Services
    _info "Enabling services"
    _chroot 'systemctl enable gdm; systemctl enable org.cups.cupsd'

    # Groups
    _info "Add ${USER_name} to all groups"
    _chroot \
        'usermod -aG root,bin,daemon,sys,adm,tty,disk,lp,mem,kmem,wheel $USER_name
        usermod -aG ftp,mail,uucp,log,utmp,locate,rfkill,smmsp,proc $USER_name
        usermod -aG http,games,lock,uuidd,dbus,network,video,audio $USER_name
        usermod -aG optical,floppy,storage,scanner,input,power,nobody $USER_name
        usermod -aG users,systemd-journal,systemd-journal-gateway $USER_name
        usermod -aG systemd-timesync,systemd-network,systemd-bus-proxy $USER_name
        usermod -aG systemd-resolve,systemd-coredump,gdm,kvm,rtkit $USER_name
        usermod -aG systemd-journal-upload,systemd-journal-remote $USER_name
        usermod -aG polkitd,git,avahi,usbmux,colord,ntp,brlapi $USER_name'
}
