#!/bin/bash

_user_infos() {

    # Hostname
    until [[ ${#HOST_name} -ge 3 \
    && ${HOST_name} =~ ^[a-zA-Z0-9][-a-zA-Z0-9_]+$ ]]; do
    _prompt "Enter Hostname (ex: my-favorite-computer):"
    read HOST_name
    done

    # Password
    until [[ ${#a} -ge 8 && "$a" == *[a-z]* && "$a" == *[0-9]* ]]; do
    _note "password should be at least 8 chars long with 1 letter and 1 digit"
    _prompt "Enter password for root:"
    read -s a
    done; echo
    _prompt "Confirm password for root:"
    read -s ROOT_passwd
    if [[ ${ROOT_passwd} != ${a} ]]; then
        _error "passwords does not match!"
    fi; echo

    # Username
    until [[ ${#USER_name} -ge 3 \
    && ${USER_name} =~ ^[a-zA-Z0-9][-a-zA-Z0-9_]+$ ]]; do
    _prompt "Enter Username (ex: johnny):"
    read USER_name
    done

    # Password
    until [[ ${#b} -ge 8 && "$b" == *[a-z]* && "$b" == *[0-9]* ]]; do
    _note "password should be at least 8 chars long with 1 letter and 1 digit"
    _prompt "Enter password for ${USER_name}:"
    read -s b
    done; echo
    _prompt "Confirm password for ${USER_name}:"
    read -s USER_passwd
    if [[ ${USER_passwd} != ${b} ]]; then
        _error "passwords does not match!"
    fi; echo

    # Desktop Environment
    _confirm "Do you wish to install Desktop Environment?"
    if [[ ${confirm} == "y" ]]; then
        until [[ ${c} == "1" || ${c} == "2" || ${c} == "3" || ${c} == "4" ]]; do
        _prompt "KDE $red[1]$green - Gnome $red[2]$green - Xfce4 $red[3]$green - Lxde $red[4]"
        read c
        done
        choice=(none,kde,gnome,xfce,lxde); desktop=${choice[${c}]}
        echo $desktop; export desktop
    fi; unset confirm

    # Export
    export HOST_name; export ROOT_passwd; export USER_name; export USER_passwd
}

_user_settings() {

    # Adding user
    _info "Setting user"
    _chroot \
        'useradd -g users -m -s /bin/bash $USER_name
        echo "${USER_name}:${USER_passwd}" | chpasswd
        echo "${USER_name} ALL=(ALL) ALL" >> /etc/sudoers'

    # Setting Aliases
    _info "Setting aliases"
    _chroot \
        'echo "export VISUAL=\"nano\"" >> /home/$USER_name/.bashrc \
        echo "alias _system=\"inxi -F -M\"" >> /home/$USER_name/.bashrc \
        echo "alias _install=\"yaourt -S\"" >> /home/$USER_name/.bashrc \
        echo "alias _delete=\"yaourt -Rcsn\"" >> /home/$USER_name/.bashrc \
        echo "alias _update=\"yaourt -Syyua\"" >> /home/$USER_name/.bashrc \
        echo "alias _clean=\"yaourt -Scc\"" >> /home/$USER_name/.bashrc \
        echo "alias _purge=\"yaourt -Qdt\"" >> /home/$USER_name/.bashrc \
        echo "alias _verif=\"yaourt -Qqk\"" >> /home/$USER_name/.bashrc \
        echo "alias _pacnew=\"yaourt -C\"" >> /home/$USER_name/.bashrc \
        echo "alias _search=\"yaourt -s\"" >> /home/$USER_name/.bashrc \
        echo "alias _mirrorlist=\"sudo reflector -c FR --sort rate --save /etc/pacman.d/mirrorlist\"" >> /home/$USER_name/.bashrc'
}
