#!/bin/bash

_install-desktop() {

    # Intel Microcode
    lscpu | grep "Intel" >/dev/null 2>&1
    if [[ $? -eq 0 ]]; then
        _info "Installing Intel CPU Microcode"
        _chroot 'pacman --noconfirm -S intel-ucode'
    fi

    # GPU Driver
    _info "Installing VGA Driver"
    _chroot 'pacman --noconfirm -S $GPU_driver'

    # File System
    _info "Installing File System"
    _chroot 'pacman --noconfirm -S gamin gvfs gvfs-mtp gvfs-nfs \
        gvfs-afc gparted ntfs-3g dosfstools exfat-utils \
        file-roller ifuse fuseiso unrar'

    # Xfce4
    _info "Installing Xfce4"
    _chroot 'pacman --noconfirm -S xfce4 xfce4-goodies'

    # LXDM
    _info "Installing LXDM"
    _chroot 'pacman --noconfirm -S lxdm'

    # Firefox
    _info "Installing Firefox"
    _chroot 'pacman --noconfirm -S firefox firefox-i18n-fr \
        hunspell-fr flashplugin'

    # Java
    _info "Installing Java"
    _chroot 'pacman --noconfirm -S jre8-openjdk'

    # Libreoffice
    _info "Installing Libreoffice"
    _chroot 'pacman --noconfirm -S libreoffice libreoffice-fr'

    # Gimp
    _info "Installing Gimp"
    _chroot 'pacman --noconfirm -S gimp'

    # Cups
    _info "Installing Cups"
    _chroot 'pacman --noconfirm -S cups cups-pdf ghostscript \
        gutenprint sane simple-scan'

    # Fonts
    _info "Installing Fonts"
    _chroot 'pacman --noconfirm -S xorg-fonts-type1 ttf-dejavu artwiz-fonts \
        font-bh-ttf font-bitstream-speedo gsfonts sdl_ttf \
        ttf-bitstream-vera ttf-cheapskate ttf-liberation \
        ttf-freefont ttf-arphic-uming ttf-baekmuk'

     # Multimedia
    _info "Installing Multimedia"
    _chroot 'pacman --noconfirm -S pulseaudio pulseaudio-alsa pavucontrol \
        parole vlc guvcview mediainfo-gui ffmpegthumbnailer'

    # Desktop Tools
    _info "Installing Desktop Tools"
    _chroot 'pacman --noconfirm -S docky gnome-calculator fbreader mupdf'

    # Network Apps
    _info "Installing Network Apps"
    _chroot 'pacman --noconfirm -S network-manager-applet \
        networkmanager-openvpn'
}

_desktop-settings() {

    # Keyboard layout
    _info "Setting keyboard layout"
    _chroot 'localectl --no-convert set-x11-keymap fr'

    # Setting LXDM
    _info "Setting LXDM"
    wget https://raw.githubusercontent.com/grm34/archboot/master/conf/lxdm_xfce.conf
    rm /mnt/etc/lxdm/lxdm.conf; cp lxdm_xfce.conf /mnt/etc/lxdm/lxdm.conf

    # Themes & icons
    _info "Adding some themes & icons"
    wget https://raw.githubusercontent.com/grm34/archboot/master/data/xfce.tar.xz
    tar xf xfce.tar.xz -C /mnt/home/$USER_name/ && rm xfce.tar.xz

    # Services
    _info "Enabling services"
    _chroot 'systemctl enable lxdm; systemctl enable org.cups.cupsd'

    # Groups
    _info "Add ${USER_name} to all groups"
    _chroot 'usermod -aG root,bin,daemon,sys,adm,tty,disk,lp,mem,kmem,wheel $USER_name; \
        usermod -aG ftp,mail,uucp,log,utmp,locate,rfkill,smmsp,proc $USER_name; \
        usermod -aG http,games,lock,uuidd,dbus,network,video,audio $USER_name; \
        usermod -aG optical,floppy,storage,scanner,input,power,nobody $USER_name; \
        usermod -aG users,systemd-journal,systemd-journal-gateway $USER_name; \
        usermod -aG systemd-timesync,systemd-network,systemd-bus-proxy $USER_name; \
        usermod -aG systemd-resolve,systemd-coredump,lxdm,kvm $USER_name; \
        usermod -aG systemd-journal-upload,systemd-journal-remote $USER_name; \
        usermod -aG polkitd,git,avahi,usbmux,colord,ntp,nm-openvpn $USER_name'
}
