#!/bin/bash

_yaourt() {

    # Setting pacman.conf
    _info "Setting pacman.conf"
    echo "## CUSTOM PACMAN.CONF ##" > /mnt/etc/pacman.conf
    echo "[options]" >> /mnt/etc/pacman.conf
    echo "HoldPkg     = pacman glibc" >> /mnt/etc/pacman.conf
    echo "Architecture = auto" >> /mnt/etc/pacman.conf
    echo "ILoveCandy" >> /mnt/etc/pacman.conf
    echo "CheckSpace" >> /mnt/etc/pacman.conf
    echo "SigLevel    = Required DatabaseOptional" >> /mnt/etc/pacman.conf
    echo "LocalFileSigLevel = Optional" >> /mnt/etc/pacman.conf
    echo "[archlinuxfr]" >> /mnt/etc/pacman.conf
    echo "SigLevel = Never" >> /mnt/etc/pacman.conf
    echo "Server = http://repo.archlinux.fr/\$arch" >> /mnt/etc/pacman.conf
    echo "[core]" >> /mnt/etc/pacman.conf
    echo "Include = /etc/pacman.d/mirrorlist" >> /mnt/etc/pacman.conf
    echo "[extra]">> /mnt/etc/pacman.conf
    echo "Include = /etc/pacman.d/mirrorlist" >> /mnt/etc/pacman.conf
    echo "[community]" >> /mnt/etc/pacman.conf
    echo "Include = /etc/pacman.d/mirrorlist" >> /mnt/etc/pacman.conf
    echo "[multilib]" >> /mnt/etc/pacman.conf
    echo "Include = /etc/pacman.d/mirrorlist" >> /mnt/etc/pacman.conf

   # Setting Mirrors
    _info "Setting mirrorlist"
    _chroot 'reflector -c FR --sort rate --save /etc/pacman.d/mirrorlist'

    # Install yaourt
    _info "Installing yaourt"
    _chroot 'pacman --noconfirm -Syu yaourt customizepkg'
}
