#!/bin/bash

_yaourt() {

    # Setting pacman.conf
    _info "Setting pacman.conf"
    _chroot 'echo "## CUSTOM PACMAN.CONF ##" > /etc/pacman.conf \
        echo "[options]" >> /etc/pacman.conf \
        echo "HoldPkg     = pacman glibc" >> /etc/pacman.conf \
        echo "Architecture = auto" >> /etc/pacman.conf \
        echo "ILoveCandy" >> /etc/pacman.conf \
        echo "CheckSpace" >> /etc/pacman.conf \
        echo "SigLevel    = Required DatabaseOptional" >> /etc/pacman.conf \
        echo "LocalFileSigLevel = Optional" >> /etc/pacman.conf \
        echo "[archlinuxfr]" >> /etc/pacman.conf \
        echo "SigLevel = Never" >> /etc/pacman.conf \
        echo "Server = http://repo.archlinux.fr/\$arch" >> /etc/pacman.conf \
        echo "[core]" >> /etc/pacman.conf \
        echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf \
        echo "[extra]">> /etc/pacman.conf \
        echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf \
        echo "[community]" >> /etc/pacman.conf \
        echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf \
        echo "[multilib]" >> /etc/pacman.conf \
        echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf'

   # Setting Mirrors
    _info "Setting mirrorlist"
    _chroot 'reflector -c FR --sort rate --save /etc/pacman.d/mirrorlist'

    # Install yaourt
    _info "Installing yaourt"
    _chroot 'pacman --noconfirm -Syu yaourt customizepkg'
}
